name: Feature request
description: Suggest an idea for this project
title: "[Feature Request] Short description"
labels: ["enhancement",]
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen, including key criteria and tasks that denote or are required for successful completion/resolution.
      value: |
        - [ ] aspect/task 1
        - [ ] ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      value: |
        | alternative | reason(s) why unsuitable |
        |---|---|
        | alt 1 | reason, reason, ... |
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here. Include any links to related issues and/or pull requests (including in other repositories).
    validations:
      required: false
